FROM  mediawiki:stable

COPY etc /etc

COPY entrypoint.sh /entrypoint.sh

RUN apt-get update \
    && apt-get install -y \
        bash \
        ncdu \
        htop \
        mtr \
        ghostscript \
        iputils-ping \
        nmap \
        openssh-server \
        sudo \
        vim \
        wget \
        xpdf-utils \
        cron \
        rclone \
        mariadb-client \
        apt-file \
        zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://tailscale.com/install.sh | sh 

RUN mkdir /run/sshd

RUN chmod 750 /etc/sudoers.d -R 

RUN chmod +x /entrypoint.sh 

SHELL ["/bin/bash"]
ENTRYPOINT /entrypoint.sh
