<?php
# This file was automatically generated by the MediaWiki 1.39.8
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

//error_reporting( E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING );
//ini_set( 'display_errors', 0 );

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "WIKIFULL";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
#$wgScriptPath = "";
$wgScriptPath = "/w";
$wgArticlePath = "/doc/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wikifull.addressforall.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
        '1x' => "$wgResourceBasePath/resources/assets/logo_a4a.png",
        'icon' => "$wgResourceBasePath/resources/assets/logo_a4a.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "xxx@gmail.com";
$wgPasswordSender = "xxx@gmail.com";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "database";
$wgDBname = "wikidb";
$wgDBuser = "wikiuser";
$wgDBpassword = "xxx";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "pt-br";

# Time zone
$wgLocaltimezone = "America/Sao_Paulo";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "xxx";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "xxx";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by/4.0/";
$wgRightsText = "Creative Commons - Atribuição";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
#wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'GeoData' );
wfLoadExtension( 'MobileFrontend' );
wfLoadExtension( 'ConfirmAccount' );
wfLoadExtension( 'UserMerge' );
//wfLoadExtension( 'EmbedVideo' );
wfLoadExtension( 'JsonConfig' );
wfLoadExtension( 'Graph' );
wfLoadExtension( 'Kartographer' );

wfLoadExtension( 'UserMerge' );

wfLoadExtension( 'LookupUser' );
$wgGroupPermissions['sysop']['lookupuser'] = true;

// By default nobody can use this function, enable for bureaucrat?
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

// To enable for administrators add this:
$wgGroupPermissions['sysop']['usermerge'] = true;



$wgFavicon = '/resources/assets/logo_a4a.png';

$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoEngineConf['luastandalone']['luaPath'] = '/usr/bin/lua5.1';


$wgKartographerMapServer = 'https://a.tile.openstreetmap.org/';
$wgKartographerDfltStyle = '';
$wgKartographerStyles = [];



// --------------------------------------------------

define("NS_OSMC", 3000); // Docs OSM Codes
define("NS_OSMC_TALK", 3001);

define("NS_OSMCX", 3002); // lixo deletar
define("NS_OSMCX_TALK", 3003);

define("NS_A4A", 3004); // Docs AddressForAll
define("NS_A4A_TALK", 3005);

define("NS_DG", 3006); // Docs Digital-guard
define("NS_DG_TALK", 3007);

define("NS_SUP", 3008); // Docs Support (suporte)
define("NS_SUP_TALK", 3009);

define("NS_SITE", 3010); // Docs for site requirements
define("NS_SITE_TALK", 3011);

define("NS_WEB", 3012); // Docs for site requirements
define("NS_WEB_TALK", 3013);

// Add namespaces.

$wgExtraNamespaces[NS_OSMC] = "afac";
$wgExtraNamespaces[NS_OSMC_TALK] = "afac_talk";

$wgExtraNamespaces[NS_OSMCX] = "osmcx";
$wgExtraNamespaces[NS_OSMCX_TALK] = "osmcx_talk";
$wgExtraNamespaces[NS_DG] = "dg";
$wgExtraNamespaces[NS_DG_TALK] = "dg_talk";
$wgExtraNamespaces[NS_A4A] = "a4a";
$wgExtraNamespaces[NS_A4A_TALK] = "a4a_talk";
$wgExtraNamespaces[NS_SUP] = "sup";
$wgExtraNamespaces[NS_SUP_TALK] = "sup_talk";
$wgExtraNamespaces[NS_SITE] = "site";
$wgExtraNamespaces[NS_SITE_TALK] = "site_talk";
$wgExtraNamespaces[NS_WEB] = "web";
$wgExtraNamespaces[NS_WEB_TALK] = "web_talk";


$wgVisualEditorAvailableNamespaces = [
    NS_MAIN => true,
    NS_USER => true,
    NS_HELP => true,
    NS_OSMC => true,
    NS_A4A => true,
    NS_DG => true,
    NS_SUP => true,
    NS_SITE => true,
    NS_WEB => true,
    "_merge_strategy" => "array_plus"
];


# Enable subpages in the namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_OSMC] = true;
$wgNamespacesWithSubpages[NS_A4A] = true;
$wgNamespacesWithSubpages[NS_DG] = true;
$wgNamespacesWithSubpages[NS_HELP] = true;
$wgNamespacesWithSubpages[NS_SUP] = true;
$wgNamespacesWithSubpages[NS_SITE] = true;
$wgNamespacesWithSubpages[NS_WEB] = true;


$wgCanonicalServer = "https://wikifull.addressforall.org";
$wgGroupPermissions['sysop']['createaccount'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
// https://www.mediawiki.org/wiki/Extension_talk:ConfirmAccount
$wgAccountRequestThrottle=false;


// https://www.mediawiki.org/wiki/Topic:T6uzpn51mgb8n5sc
$wgRunJobsAsync=false;
$wgJobRunRate = 0.01;



// anonimo não edita
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['sysop']['edit'] = true;

// para a aprovação de usuaários pelo admin, sem isso não funciona
$wgGroupPermissions['bureaucrat']['createaccount'] = true;


// Debug SQL - Carlos 10/10/2023
/*
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgShowSQLErrors = true;
$wgShowExceptionDetails = true;
error_reporting( -1 );
ini_set( 'display_errors', 1 );
 */
/*
$wgShowExceptionDetails = true;
$wgDebugToolbar = true;
$wgShowDebug = true;
$wgDevelopmentWarnings = true;
 */


$wgMaxUploadSize = 1024 * 1024 * 200;




# /var/www/html/w
$wgDebugLogGroups['Translate'] = '/var/www/html/translate.log';


//---------------------------------------------------------------
