# Wiki stack
#
# Env:
# WEBSERVER_FQDN
# WIKI_USER
# WIKI_PASSWORD

version: '3.8'

configs:
  prompt_bashrc:
    name: prompt_bashrc
    external: true
  sshd_config:
    name: sshd_config_v2
    external: true
  sshd_pam:
    name: sshd_pam_v1
    external: true
  wiki-passwd:
    name: wiki-passwd
    external: true

services:

  server:
    #image: marcelofmatos/mediawiki:1.27
    #image: mediawiki:stable
    image: dockerhub.itgs.org.br/itgs/wiki:main
    environment:
      MEDIAWIKI_SERVER: https://wikifull.addressforall.org
      MEDIAWIKI_SITENAME: "A4A Wiki"
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: database
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_PASSWORD: xxx
      MEDIAWIKI_LANGUAGE_CODE: pt-BR
      MEDIAWIKI_DEBUG: 1
      WIKI_USER: admin
      WIKI_PASSWORD: xxx
      TZ: America/Sao_Paulo
    volumes:
      #- www:/var/www/mediawiki
      - www:/var/www/html
      - home:/home
    networks:
      - default
      - web
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints:
          - node.labels.app == true
      labels:
        - traefik.enable=true
        - traefik.http.services.addressforall-wikifull.loadbalancer.server.port=80
        - traefik.http.routers.addressforall-wikifull.entrypoints=websecure
        - traefik.http.routers.addressforall-wikifull.tls.certresolver=myresolver
        - traefik.http.routers.addressforall-wikifull.rule=Host(`wikifull.addressforall.org`)

  ssh:
    #image: biosludge/sshd:latest
    image: dockerhub.itgs.org.br/itgs/wiki:sshd
    cap_add:
      - NET_ADMIN
    command: "wiki:xxx:1000:33"
    #entrypoint: "tail -f /etc/hosts"
    hostname: wikifull.addressforall.org
    environment:
      WEBSERVER_FQDN: wikifull.addressforall.org
      SSH_PASSWORD: xxx
    #working_dir: /var/www/html
    configs:
      - source: sshd_config
        target: /etc/ssh/sshd_config.d/custom.conf


    volumes:
      - www:/var/www/html
      - home:/home
      - var-spool-cron:/var/spool/cron
      - root:/root
      - tailscale:/var/lib/tailscale/
    ports:
      - 2221:22
    deploy:
      mode: replicated
      #restart_policy:
      #  condition: none
      replicas: 1
      placement:
         constraints:
          - node.labels.app == true
      
  database:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: xxx
      MYSQL_ROOT_PASSWORD: baEdejELp5ozg
      TZ: America/Sao_Paulo
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints:
          - node.labels.database == true
      
networks:
  web: # proxy net
    external: true
    name: proxy


volumes:
  tailscale:
    driver: local
  root:
    driver: local
  www:
    driver: local
  home:
    driver: local
  var-spool-cron:
    driver: local
  mysql-data:
    driver: local
